pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins

  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.23.2-debug
    command: ["sleep"]
    args: ["3600"]
    tty: true

    volumeMounts:
    - name: docker-config
      mountPath: /kaniko/.docker/

  volumes:
  - name: docker-config
    secret:
      secretName: ecr-secret
      items:
      - key: .dockerconfigjson
        path: config.json
"""
    }
  }

  environment {
    AWS_REGION = "eu-central-1"
    ECR_REPO   = "683966916235.dkr.ecr.eu-central-1.amazonaws.com/django-app"
    IMAGE_TAG  = "${BUILD_NUMBER}"
    HELM_REPO  = "https://github.com/Natalina686/my-microservice-project.git"
    GIT_BRANCH = "main"
  }

  options {
    disableConcurrentBuilds()
  }

  stages {

    stage('Checkout App') {
  steps {
    git branch: 'main',
        url: 'https://github.com/Natalina686/my-microservice-project.git'
  }
}


    stage('Verify Kaniko') {
      steps {
        container('kaniko') {
          sh '''
            /kaniko/executor --help | head -n 5
          '''
        }
      }
    }

    stage('Build & Push Image to ECR') {
  steps {
    container('kaniko') {
      sh '''
        set -e

        CONTEXT=$WORKSPACE/django-docker-project/app

        ls -la $CONTEXT

        /kaniko/executor \
          --context=$CONTEXT \
          --dockerfile=$CONTEXT/Dockerfile \
          --destination=$ECR_REPO:$IMAGE_TAG \
          --cache=true \
          --cleanup \
          --use-new-run
      '''
    }
  }
}

    stage('Clone Helm Repo') {
      steps {
        sh """
          rm -rf helm-repo
          git clone $HELM_REPO helm-repo
        """
      }
    }

    stage('Update Helm values') {
      steps {
        sh """
          cd helm-repo

          sed -i "s/tag:.*/tag: ${IMAGE_TAG}/" charts/django-app/values.yaml

          git config user.email "jenkins@ci.local"
          git config user.name "jenkins"

          git add charts/django-app/values.yaml

          git diff --cached --quiet && echo "No changes" && exit 0

          git commit -m "ci: update image tag ${IMAGE_TAG}"
          git push origin $GIT_BRANCH
        """
      }
    }
  }

  post {
    success {
      echo "SUCCESS: Image built + pushed to ECR + Helm updated"
    }

    failure {
      echo "FAILED: check Kaniko / ECR / permissions"
    }
  }
}