apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DEBUG: "True"
  SECRET_KEY: "super-secret-key"
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"